### ISSUE TITLE
No working properly

### ISSUE THREAD

**Issue by rohankumar20** [roshan9419/PersonalAssistantChatbot#2]
Every thing is open browser
Create a empty file  not able do 
What is weather opening in browser

**Comment by roshan9419** [comment]
Hey, try to check command line logs. Some error would appear when you say "create a empty file". Open fileHandler.py file and change the appLocation path, you're good to go then. 
If you don't want to open the browser everytime the command you spoke is not available then you can comment the line in GUIASSISTANT.py file in main() at last.
